### Get games
GET http://localhost:5299/games

### Get game 1
GET http://localhost:5299/games/1

### Create game
POST http://localhost:5299/games
Content-Type: application/json

{
  "boardSize": 3
}

### Join game 1
PUT http://localhost:5299/games/1/join