### Health
GET http://localhost:8080/health

### Get games
GET http://localhost:8080/games

### Get game 1
GET http://localhost:8080/games/4

### Create game
POST http://localhost:8080/games
Content-Type: application/json

{
  "boardSize": 20,
  "winCondition": 10
}

### Take move X
PUT http://localhost:8080/games/4/move
Content-Type: application/json

{
  "player": "X",
  "row": 4,
  "column": 1
}

### Take move O
PUT http://localhost:8080/games/4/move
Content-Type: application/json

{
  "player": "O",
  "row": 4,
  "column": 0
}