### Health
GET http://localhost:8080/health

### Get games
GET http://localhost:8080/games

### Get game 1
GET http://localhost:8080/games/1

### Create game
POST http://localhost:8080/games
Content-Type: application/json

### Take move X
PUT http://localhost:8080/games/1/move
Content-Type: application/json

{
  "player": "X",
  "row": 0,
  "column": 1
}

### Take move O
PUT http://localhost:8080/games/1/move
Content-Type: application/json

{
  "player": "O",
  "row": 2,
  "column": 0
}