### Get games
GET http://localhost:5299/games

### Get game 1
GET http://localhost:5299/games/1

### Create game
POST http://localhost:5299/games
Content-Type: application/json

{
  "boardSize": 3,
  "winCondition": 3
}

### Take move X
PUT http://localhost:5299/games/1/move
Content-Type: application/json

{
  "gameId": 0,
  "player": "X",
  "row": 1,
  "column": 2
}

### Take move O
PUT http://localhost:5299/games/1/move
Content-Type: application/json

{
  "gameId": 0,
  "player": "O",
  "row": 2,
  "column": 1
}