### Get games
GET http://localhost:5299/games

### Get game 1
GET http://localhost:5299/games/0

### Create game
POST http://localhost:5299/games
Content-Type: application/json

{
  "boardSize": 3,
  "winCondition": 3
}

### Take move
PUT http://localhost:5299/games/0/move
Content-Type: application/json

{
  "gameId": 0,
  "player": "X",
  "row": 0,
  "column": 0
}

### Join game 1
#PUT http://localhost:5299/games/0/join